# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97da4703eaba4f99c0c9c2d2d80152b2c04ec41adfa92e7b192e847f05425126285274eef91e4ae0fe433cf15cc7e0d06cdd29fb63a77a4ef5815c624fb20958

test:
  secret_key_base: 82db850f7d8257dd9d112ec7934fbfcef4607b950610fc3d6f4dd4d100cc681faf5645d546444fc7ef299f24b0abf90244495dec0b3b093784a2986606979b1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
